In [2]:
import numpy as np

In [3]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

a2 = np.array([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3], [4,4,4,4]],
    [[5,5,5,5], [6,6,6,6], [7,7,7,7], [8,8,8,8]],
    [[9,9,9,9], [10,10,10,10], [11,11,11,11], [12,12,12,12]],
    [[13,13,13,13], [14,14,14,14], [15,15,15,15], [16,16,16,16]],
])

In [6]:
a2[..., 3][..., None]

array([[[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4]],

       [[ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8]],

       [[ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12]],

       [[13, 13, 13],
        [14, 14, 14],
        [15, 15, 15],
        [16, 16, 16]]])

In [15]:
def blend_colors_with_weights(weights: np.ndarray, color1: np.ndarray, color2: np.ndarray) -> np.ndarray:
    # Ensure colors are numpy arrays with shape (3,)
    color1 = np.array(color1)
    color2 = np.array(color2)
    
    # Ensure weights is a 2D numpy array
    assert weights.ndim == 2, "Weights must be a 2D numpy array"
    
    # Reshape the weights array to be compatible with the color arrays
    weights = weights[:, :, np.newaxis]
    
    # Blend the colors using the weights
    blended_colors = (1 - weights) * color1 + weights * color2
    
    # Convert the result to integer type if needed
    blended_colors = blended_colors.astype(int)
    
    return blended_colors

# Example usage
weights = np.random.rand(4, 4)  # 2D array of weights between 0 and 1
color1 = np.array([255, 0, 0])  # Red
color2 = np.array([0, 0, 255])  # Blue

blended = blend_colors_with_weights(weights, color1, color2)

print("Weights array (4x4):")
print(weights)
print("\nBlended colors array (4x4x3):")
print(blended)

Weights array (4x4):
[[0.81822702 0.99193731 0.27509481 0.09746435]
 [0.16537551 0.47399247 0.16797415 0.15813634]
 [0.28713503 0.40933462 0.8707105  0.43175981]
 [0.45985526 0.13158388 0.26332139 0.86702887]]

Blended colors array (4x4x3):
[[[ 46   0 208]
  [  2   0 252]
  [184   0  70]
  [230   0  24]]

 [[212   0  42]
  [134   0 120]
  [212   0  42]
  [214   0  40]]

 [[181   0  73]
  [150   0 104]
  [ 32   0 222]
  [144   0 110]]

 [[137   0 117]
  [221   0  33]
  [187   0  67]
  [ 33   0 221]]]


In [26]:
color1 = (0, 0, 0)
color2 = (255, 255, 255)

color1_to_color2_weights = np.array([
    [0.01, 0.02, 0.03, 0.04],
    [0.05, 0.06, 0.07, 0.08],
    [0.09, 0.10, 0.11, 0.12],
    [0.13, 0.14, 0.15, 0.16]
])

color1_to_color2_weights = color1_to_color2_weights[:, :, np.newaxis]

blended_colors = (1 - color1_to_color2_weights) * color1 + color1_to_color2_weights * color2
blended_colors

array([[[ 2.55,  2.55,  2.55],
        [ 5.1 ,  5.1 ,  5.1 ],
        [ 7.65,  7.65,  7.65],
        [10.2 , 10.2 , 10.2 ]],

       [[12.75, 12.75, 12.75],
        [15.3 , 15.3 , 15.3 ],
        [17.85, 17.85, 17.85],
        [20.4 , 20.4 , 20.4 ]],

       [[22.95, 22.95, 22.95],
        [25.5 , 25.5 , 25.5 ],
        [28.05, 28.05, 28.05],
        [30.6 , 30.6 , 30.6 ]],

       [[33.15, 33.15, 33.15],
        [35.7 , 35.7 , 35.7 ],
        [38.25, 38.25, 38.25],
        [40.8 , 40.8 , 40.8 ]]])

In [8]:
np.pad(a2, ((0, 0), (0, 1), (0, 0)), mode='constant', constant_values=0)

array([[[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 0,  0,  0]],

       [[ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 0,  0,  0]],

       [[ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12],
        [ 0,  0,  0]],

       [[13, 13, 13],
        [14, 14, 14],
        [15, 15, 15],
        [16, 16, 16],
        [ 0,  0,  0]]])

In [ ]:
# this is copied RIGHT from chatgpt and im NOT afraid to say it

import numpy as np

def blend_colors(original: np.ndarray, new: np.ndarray) -> np.ndarray:
    # Ensure the original array has 3 channels and the new array has 4 channels
    assert original.shape[:2] == new.shape[:2], "The first two dimensions must match"
    assert original.shape[2] == 3, "The original array must have 3 channels"
    assert new.shape[2] == 4, "The new array must have 4 channels"

    # Extract RGB and alpha components
    new_rgb = new[..., :3]
    new_alpha = new[..., 3] / 255.0

    # Perform the blending
    blended_rgb = (new_rgb * new_alpha[..., np.newaxis] + 
                   original * (1 - new_alpha[..., np.newaxis]))

    # Convert to integer type
    blended_rgb = blended_rgb.astype(int)

    return blended_rgb

# Example usage
original = np.random.randint(0, 256, (4, 4, 3), dtype=int)
new = np.random.randint(0, 256, (4, 4, 4), dtype=int)

print("Original array (4x4x3):")
print(original)
print("\nNew array (4x4x4):")
print(new)

blended = blend_colors(original, new)
print("\nBlended array (4x4x3):")
print(blended)
