In [1]:
import numpy as np

In [3]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

a2 = np.array([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3], [4,4,4,4]],
    [[5,5,5,5], [6,6,6,6], [7,7,7,7], [8,8,8,8]],
    [[9,9,9,9], [10,10,10,10], [11,11,11,11], [12,12,12,12]],
    [[13,13,13,13], [14,14,14,14], [15,15,15,15], [16,16,16,16]],
])

In [6]:
b1 = np.array([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3], [4,4,4,4]],
    [[5,5,5,5], [6,6,6,6], [7,7,7,7], [8,8,8,8]],
])

b2 = np.array([
    [[9,9,9,9], [10,10,10,10], [10,10,10,10], [12,12,12,12]],
    [[13,13,13,13], [14,14,14,14], [14,14,14,14], [16,16,16,16]],
])

In [8]:
def compare_adjacent_columns(color_strip):
    # Ensure the input array is a numpy array
    color_strip = np.asarray(color_strip)
    
    # We assume color_strip shape is (2, n, 4)
    # Calculate differences between adjacent columns
    differences = np.any(color_strip[:, 1:] != color_strip[:, :-1], axis=(0, 2))
    
    # differences will be a 1D numpy array where True indicates the current column is different from the previous one
    return differences
compare_adjacent_columns(b2)


array([ True, False,  True])

In [16]:
def vectorized_distances_to_true(bool_array):
    # Ensure input is a numpy array
    bool_array = np.asarray(bool_array)
    
    # Find the indices where the array is True
    true_indices = np.where(bool_array)[0]
    
    # Calculate the distances between consecutive True indices
    if len(true_indices) == 0:
        return []  # Return an empty list if there are no True values

    # Distances between consecutive Trues
    distances = np.diff(true_indices) - 1

    # Include distance from the start to the first True if it starts with False
    if true_indices[0] != 0:
        distances = np.insert(distances, 0, true_indices[0])

    return distances.tolist()

In [21]:
input_array = [False, False, False, True, False, False, False, True]
output = vectorized_distances_to_true(input_array)
print(input_array)
print(output)  # Output will be [3, 3]


[False, False, False, True, False, False, False, True]
[3, 3]


In [23]:
color_strip = np.array([
    [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [2, 2, 2], [1, 1, 1],[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [2, 1, 1]],
    [[1, 1, 1], [2, 1, 1], [1, 1, 1], [1, 1, 1], [2, 2, 2], [1, 1, 1],[9, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [9, 1, 1]],
])
test1 = np.any(color_strip[:, 1:] != color_strip[:, :-1], axis=(0, 2))
print(test1)

print(vectorized_distances_to_true(test1))

[ True  True False  True  True  True  True False False False  True]
[0, 1, 0, 0, 0, 3]


In [26]:
def false_chunk_sizes(bool_array):
    # Ensure the input is a numpy array
    bool_array = np.asarray(bool_array)

    # Find where the transitions occur
    transitions = np.diff(bool_array)
    # Identify the start indices of False chunks
    false_starts = np.where(transitions == -1)[0] + 1
    # Identify the end indices of False chunks
    false_ends = np.where(transitions == 1)[0]

    # Handle the case when the array starts with False
    if bool_array[0] == False:
        false_starts = np.insert(false_starts, 0, 0)

    # Handle the case when the array ends with False
    if bool_array[-1] == False:
        false_ends = np.append(false_ends, len(bool_array) - 1)

    # Calculate the sizes of the false chunks
    false_sizes = false_ends - false_starts + 1

    return false_sizes.tolist()

input_array = np.array([True, False, False, False, True, True, False, False, True])
output = false_chunk_sizes(input_array)
print(output)  # Output will be [3, 2]


ValueError: operands could not be broadcast together with shapes (4,) (0,) 

In [42]:
input_array = np.array([False, False, True, False, False, False, True, True, False, False, True, False])

diffs = np.diff(input_array)
changes = np.where(diffs == True)[0] + 1

# edge cases - count chunks at start or end of input
if input_array[0] == False:
    changes = np.insert(changes, 0, 0)

# Handle the case when the array ends with False
if input_array[-1] == False:
    changes = np.append(changes, len(input_array))

print(diffs)
print(changes)

# every even index is the start of a false chunk
# every odd index is the end of a false chunk (exclusive)

# return odd - even elements (those are the sizes)

sizes = changes[1::2] - changes[::2]
print(sizes)


TypeError: append() missing 1 required positional argument: 'values'

In [15]:
def vectorized_distances_to_false(bool_array):
    # Find the indices where the array is False
    false_indices = np.where(~bool_array)[0]
    
    print(false_indices)
    
    # Calculate the distances between consecutive False indices
    if len(false_indices) == 0:
        return []  # Return an empty list if there are no False values

    # Distance to first False (for completeness if you need it, uncomment below line)
    initial_distance = false_indices[0] + 1 if false_indices[0] != 0 else 0

    # Distances between consecutive Falses
    distances = np.diff(false_indices) - 1

    # Include distance from the start to the first False if it starts with True
    if false_indices[0] == 0:
        distances = np.insert(distances, 0, false_indices[0])

    return distances.tolist()

test_arr = np.array([False, True, True, False, True, False, False, True, True, False, False, False, True])
print(vectorized_distances_to_false(test_arr))


[ 0  3  5  6  9 10 11]
[0, 2, 1, 0, 2, 0, 0]


In [22]:
color_strip = np.array([
    [[1, 1, 1], [1, 1, 1], [1, 1, 1], [4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4], [7, 7, 7], [8, 8, 8]],
    [[9, 9, 9], [9, 9, 9], [9, 9, 9], [12, 12, 12], [12, 12, 12], [12, 12, 12], [12, 13, 12], [12, 12, 12], [12, 12, 12], [15, 15, 15], [16, 16, 16]]
])

np.any(color_strip[:, 1:] != color_strip[:, :-1], axis=(0, 2))

array([False, False,  True, False, False,  True,  True, False,  True,
        True])

In [38]:
def distances_to_false(bool_array: np.ndarray) -> np.ndarray:
    """
    Given a 1D array of booleans, returns a 1D array of integers representing the distances between
    consecutive False values. If there are no False values, returns an empty array.
    """
    # Find the indices where the array is False
    false_indices = np.where(bool_array)[0]
    
    # Calculate the distances between consecutive False indices
    if len(false_indices) == 0:
        return np.array([])  # Return an empty list if there are no False values

    # Distances between consecutive Falses
    distances = np.diff(false_indices) - 1

    # Include distance from the start to the first False if it starts with True
    if false_indices[0] != 0:
        distances = np.insert(distances, 0, false_indices[0])

    return distances

color_strip = np.array([
    [[1, 1, 1], [1, 1, 1], [1, 1, 1], [4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4], [7, 7, 7], [8, 8, 8]],
    [[9, 9, 9], [9, 9, 9], [9, 9, 9], [12, 12, 12], [12, 12, 12], [12, 12, 12], [12, 13, 12], [12, 12, 12], [12, 12, 12], [15, 15, 15], [16, 16, 16]]
])

#colors_diffs = np.any(color_strip[:, 1:] == color_strip[:, :-1], axis=(0, 2))
colors_diffs = np.any(color_strip[:, 1:] != color_strip[:, :-1], axis=(0, 2))

dists_to_diffs = distances_to_false(colors_diffs)

print(colors_diffs)
print(dists_to_diffs)

[False False  True False False  True  True False  True  True]
[2 2 0 1 0]


In [32]:
c = np.array([1, 0, 0, 1, 1])

not c


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]:
def find_last_element(ordered_list, n):
    """
    Performs binary search to find the last tuple where the first element x is less than n.
    
    Parameters:
    ordered_list (list of tuples): A list of 2-tuples sorted by the first element in ascending order.
    n (int or float): The number to compare the first element of tuples against.
    
    Returns:
    tuple: The last tuple where the first element is less than n, or None if no such element exists.
    """
    low, high = 0, len(ordered_list) - 1
    result = None
    
    while low <= high:
        mid = (low + high) // 2
        if ordered_list[mid][0] < n:
            result = ordered_list[mid]  # Found a valid element, save it.
            low = mid + 1  # Try to find a more right-hand element with x still less than n.
        else:
            high = mid - 1  # Reduce the high boundary to skip elements not satisfying the condition.
    
    return result

# Example usage:
ordered_list = [(1, 'a'), (3, 'b'), (5, 'c'), (7, 'd'), (9, 'e')]
n = 12
print(find_last_element(ordered_list, n))  # Expected output: (5, 'c')


(9, 'e')


In [4]:
from skimage.draw import line

def draw_line(image: np.ndarray, pos1: tuple, pos2: tuple, color) -> None:
    """
    draw a fully opaque line of color `color` on the image from pos1= (x1, y1) to pos2= (x2, y2).
    modifies `image` in place, does not return anything.
    """
    
    x1, y1 = pos1
    x2, y2 = pos2
    
    # Get the coordinates of the line
    rr, cc = line(y1, x1, y2, x2)

    # Clip the coordinates to be within the image dimensions
    rr = np.clip(rr, 0, image.shape[0] - 1)
    cc = np.clip(cc, 0, image.shape[1] - 1)

    # Draw the white line (255, 255, 255) on the image
    image[rr, cc] = color
    
draw_line(a2, (0, 0), (3, 3), 255)
a2

array([[[255, 255, 255, 255],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4]],

       [[  5,   5,   5,   5],
        [255, 255, 255, 255],
        [  7,   7,   7,   7],
        [  8,   8,   8,   8]],

       [[  9,   9,   9,   9],
        [ 10,  10,  10,  10],
        [255, 255, 255, 255],
        [ 12,  12,  12,  12]],

       [[ 13,  13,  13,  13],
        [ 14,  14,  14,  14],
        [ 15,  15,  15,  15],
        [255, 255, 255, 255]]])

In [8]:
from skimage.draw import line

y1 = 0
x1 = 0
y2 = 8
x2 = 3

rr, cc = line(y1, x1, y2, x2)

rr, cc

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 2, 3, 3], dtype=int64))

In [12]:
import numpy as np
from skimage.draw import line

def draw_white_line(image, x1, y1, x2, y2):
    """
    Draws a white line on the given 2D numpy array of RGB values.

    Parameters:
        image (numpy.ndarray): 2D numpy array of RGB values.
        x1, y1 (int): Coordinates of the starting point.
        x2, y2 (int): Coordinates of the ending point.

    Returns:
        numpy.ndarray: Image with the white line drawn on it.
    """
    # Ensure the image is a numpy array
    image = np.asarray(image, dtype=np.uint8)

    # Get the coordinates of the line
    rr, cc = line(y1, x1, y2, x2)

    # Clip the coordinates to be within the image dimensions
    rr = np.clip(rr, 0, image.shape[0] - 1)
    cc = np.clip(cc, 0, image.shape[1] - 1)

    # Draw the white line (255, 255, 255) on the image
    image[rr, cc] = [255, 255, 255]

    return image

# Example usage
image = np.zeros((6, 6, 3), dtype=np.uint8)
x1, y1 = -2, 2
x2, y2 = 3, 5

result_image = draw_white_line(image, x1, y1, x2, y2)
print(image)


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [255 255 255]
  [255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [255 255 255]
  [  0   0   0]
  [  0   0   0]]]


In [7]:
a2[..., 3][..., None]

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]]])

In [1]:
def blend_colors_with_weights(weights: np.ndarray, color1: np.ndarray, color2: np.ndarray) -> np.ndarray:
    # Ensure colors are numpy arrays with shape (3,)
    color1 = np.array(color1)
    color2 = np.array(color2)
    
    # Ensure weights is a 2D numpy array
    assert weights.ndim == 2, "Weights must be a 2D numpy array"
    
    # Reshape the weights array to be compatible with the color arrays
    weights = weights[:, :, np.newaxis]
    
    # Blend the colors using the weights
    blended_colors = (1 - weights) * color1 + weights * color2
    
    # Convert the result to integer type if needed
    blended_colors = blended_colors.astype(int)
    
    return blended_colors

# Example usage
weights = np.random.rand(4, 4)  # 2D array of weights between 0 and 1
color1 = np.array([255, 0, 0])  # Red
color2 = np.array([0, 0, 255])  # Blue

blended = blend_colors_with_weights(weights, color1, color2)

print("Weights array (4x4):")
print(weights)
print("\nBlended colors array (4x4x3):")
print(blended)

NameError: name 'np' is not defined

In [5]:
camera_left = 27.5

wave_pivot_points = [
    1.2,
    1.4,
    4.5,
    6.7,
    8.9,
    11.5,
    24.2,
    24.6, 
    26.7, 
    27.1,
    27.5, 
    30.3,
    45.6,
    68.8,
]

leftmost_pivot_idx = None
# binary search for the leftmost pivot that is less than the camera_left
start, end = 0, len(wave_pivot_points) - 1
while start <= end:
    leftmost_pivot_idx = (start + end) // 2
    if wave_pivot_points[leftmost_pivot_idx] < camera_left:
        start = leftmost_pivot_idx + 1
    else:
        end = leftmost_pivot_idx - 1
        
print(leftmost_pivot_idx, wave_pivot_points[leftmost_pivot_idx])

9 27.1


In [26]:
color1 = (0, 0, 0)
color2 = (255, 255, 255)

color1_to_color2_weights = np.array([
    [0.01, 0.02, 0.03, 0.04],
    [0.05, 0.06, 0.07, 0.08],
    [0.09, 0.10, 0.11, 0.12],
    [0.13, 0.14, 0.15, 0.16]
])

color1_to_color2_weights = color1_to_color2_weights[:, :, np.newaxis]

blended_colors = (1 - color1_to_color2_weights) * color1 + color1_to_color2_weights * color2
blended_colors

array([[[ 2.55,  2.55,  2.55],
        [ 5.1 ,  5.1 ,  5.1 ],
        [ 7.65,  7.65,  7.65],
        [10.2 , 10.2 , 10.2 ]],

       [[12.75, 12.75, 12.75],
        [15.3 , 15.3 , 15.3 ],
        [17.85, 17.85, 17.85],
        [20.4 , 20.4 , 20.4 ]],

       [[22.95, 22.95, 22.95],
        [25.5 , 25.5 , 25.5 ],
        [28.05, 28.05, 28.05],
        [30.6 , 30.6 , 30.6 ]],

       [[33.15, 33.15, 33.15],
        [35.7 , 35.7 , 35.7 ],
        [38.25, 38.25, 38.25],
        [40.8 , 40.8 , 40.8 ]]])

In [8]:
np.pad(a2, ((0, 0), (0, 1), (0, 0)), mode='constant', constant_values=0)

array([[[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 0,  0,  0]],

       [[ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 0,  0,  0]],

       [[ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12],
        [ 0,  0,  0]],

       [[13, 13, 13],
        [14, 14, 14],
        [15, 15, 15],
        [16, 16, 16],
        [ 0,  0,  0]]])

In [ ]:
# this is copied RIGHT from chatgpt and im NOT afraid to say it

import numpy as np

def blend_colors(original: np.ndarray, new: np.ndarray) -> np.ndarray:
    # Ensure the original array has 3 channels and the new array has 4 channels
    assert original.shape[:2] == new.shape[:2], "The first two dimensions must match"
    assert original.shape[2] == 3, "The original array must have 3 channels"
    assert new.shape[2] == 4, "The new array must have 4 channels"

    # Extract RGB and alpha components
    new_rgb = new[..., :3]
    new_alpha = new[..., 3] / 255.0

    # Perform the blending
    blended_rgb = (new_rgb * new_alpha[..., np.newaxis] + 
                   original * (1 - new_alpha[..., np.newaxis]))

    # Convert to integer type
    blended_rgb = blended_rgb.astype(int)

    return blended_rgb

# Example usage
original = np.random.randint(0, 256, (4, 4, 3), dtype=int)
new = np.random.randint(0, 256, (4, 4, 4), dtype=int)

print("Original array (4x4x3):")
print(original)
print("\nNew array (4x4x4):")
print(new)

blended = blend_colors(original, new)
print("\nBlended array (4x4x3):")
print(blended)
