In [3]:
import numpy as np

In [6]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

a2 = np.array([
    [[1,1,1], [2,2,2], [3,3,3], [4,4,4]],
    [[5,5,5], [6,6,6], [7,7,7], [8,8,8]],
    [[9,9,9], [10,10,10], [11,11,11], [12,12,12]],
    [[13,13,13], [14,14,14], [15,15,15], [16,16,16]],
])

In [8]:
np.pad(a2, ((0, 0), (0, 1), (0, 0)), mode='constant', constant_values=0)

array([[[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 0,  0,  0]],

       [[ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 0,  0,  0]],

       [[ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12],
        [ 0,  0,  0]],

       [[13, 13, 13],
        [14, 14, 14],
        [15, 15, 15],
        [16, 16, 16],
        [ 0,  0,  0]]])

In [4]:
# this is copied RIGHT from chatgpt and im NOT afraid to say it

import numpy as np

def blend_colors(original: np.ndarray, new: np.ndarray) -> np.ndarray:
    # Ensure the original array has 3 channels and the new array has 4 channels
    assert original.shape[:2] == new.shape[:2], "The first two dimensions must match"
    assert original.shape[2] == 3, "The original array must have 3 channels"
    assert new.shape[2] == 4, "The new array must have 4 channels"

    # Extract RGB and alpha components
    new_rgb = new[..., :3]
    new_alpha = new[..., 3] / 255.0

    # Perform the blending
    blended_rgb = (new_rgb * new_alpha[..., np.newaxis] + 
                   original * (1 - new_alpha[..., np.newaxis]))

    # Convert to integer type
    blended_rgb = blended_rgb.astype(int)

    return blended_rgb

# Example usage
original = np.random.randint(0, 256, (4, 4, 3), dtype=int)
new = np.random.randint(0, 256, (4, 4, 4), dtype=int)

print("Original array (4x4x3):")
print(original)
print("\nNew array (4x4x4):")
print(new)

blended = blend_colors(original, new)
print("\nBlended array (4x4x3):")
print(blended)


Original array (4x4x3):
[[[187  62  63]
  [ 98 156 132]
  [155 190 184]
  [185 168 157]]

 [[  4 205 172]
  [ 56 233 199]
  [241 229 129]
  [ 95  68 146]]

 [[183 103  71]
  [162  73 155]
  [ 56 244  30]
  [247 202 185]]

 [[106 152  77]
  [207 147 172]
  [ 71 104 142]
  [108 158 235]]]

New array (4x4x4):
[[[157 176  70 243]
  [125 126 238 183]
  [107 222 112 241]
  [ 24 250  24  19]]

 [[169  19 240  47]
  [ 37 208 169 201]
  [ 23 252 252 222]
  [191 187 120 131]]

 [[105 173 165 211]
  [ 91 250   6  47]
  [ 88  14 246 145]
  [ 22 150 246  95]]

 [[250 146  81  53]
  [ 23  82 221 117]
  [121  53  74 106]
  [104  24 188 254]]]

Blended array (4x4x3):
[[[158 170  69]
  [117 134 208]
  [109 220 115]
  [173 174 147]]

 [[ 34 170 184]
  [ 41 213 175]
  [ 51 249 236]
  [144 129 132]]

 [[118 160 148]
  [148 105 127]
  [ 74 113 152]
  [163 182 207]]

 [[135 150  77]
  [122 117 194]
  [ 91  82 113]
  [104  24 188]]]


In [1]:
a

NameError: name 'a' is not defined